### ISSUE TITLE
invalid literal for int() with base 0: '0x'`

### ISSUE THREAD

**Issue by Mglt-b** [naseriax/pySorReader#1]
Hello do you often work on it ?

Have this error when try to run it :
python = 3.8.5

`Traceback (most recent call last):

  File "c:/Users/x/Pictures/pySorReader-main/consumer.py", line 6, in <module>     
    r = sorReader(r"yy.sor")

  File "c:\Users\x\Pictures\pySorReader-main\pySorReader.py", line 32, in __init__ 
    self.dataPts()

  File "c:\Users\x\Pictures\pySorReader-main\pySorReader.py", line 161, in dataPts 
    self.dataset[passedlen]=dB(self.hexparser(dtpoints[length*4:length*4 + 4]))

  File "c:\Users\x\Pictures\pySorReader-main\pySorReader.py", line 82, in hexparser
    return int("0x"+"".join([cleanhex[i:i+2] for i in range(0,len(cleanhex),2)][::-1]),0)

ValueError: invalid literal for int() with base 0: '0x'`

Try to add a viewer in my android application
Thanks

**Comment by naseriax** [comment]
Hi,
I use it daily, but with a specific OTDR hw only.
Please share your sor file and I will have a look.


I have a Go version as well (only provides a json output), you may try that
one in the meantime.


BR,

**Comment by Mglt-b** [comment]
Hi,
Thanks for your answer

it's really the python version that could interest me

[NRO_01024_00004-3-031-1310-OE-BRA_01024_04035.zip](https://github.com/naseriax/pySorReader/files/12437555/NRO_01024_00004-3-031-1310-OE-BRA_01024_04035.zip)

If you have time to have a look =)

thanks

**Comment by Mglt-b** [comment]
ChatGPT say this edit : 

```python
def hexparser(self, cleanhex, mode="sauber"):
    if not cleanhex:
        return 0  # ou une autre valeur par défaut appropriée

    if mode == "schmutzig":
        return int("0x" + "".join(list(map(hex, list(map(ord, cleanhex))))[::-1]).replace("0x", ""), 0)
    elif mode == "schreiben":
        return bytes.fromhex("".join([cleanhex[i:i+2] for i in range(0, len(cleanhex), 2)])).decode("latin-1")
    else:
        return int("0x" + "".join([cleanhex[i:i+2] for i in range(0, len(cleanhex), 2)][::-1]), 0)
```

Working to extract data on my file and your file

for plotter he tell me this edit  : 

```python
def ploter(self):
    c = plt.subplots(figsize=(13, 8))[1]
    c.plot(self.dataset.keys(), self.dataset.values(), color='tab:green', lw=0.6)
    
    for ev_num, event_data in self.jsonoutput["events"].items():
        event_point = event_data["eventPoint_m"]
        if event_point in self.dataset:
            eventType = event_data["eventType"]
            if eventType == "F9999OT\x00":
                eventType = "Connector"
            elif eventType == "9999OT*\x8a":
                eventType = "Connector"
            elif eventType == "99LS±Ã\x01\x00":
                eventType = "Splice"
            elif eventType == "999OT\x00\x00\x00":
                eventType = "Connector"
            else:
                eventType = "Unknown"

            c.annotate(
                f"Event: {ev_num}\nType: {eventType}\nLen: {round(event_point, 1)}m\nRef: {event_data['reflectionLoss_dB']}dB",
                xy=(event_point, self.dataset[event_point]),
                xytext=(event_point, self.dataset[event_point] - 1),
                arrowprops=dict(arrowstyle="->", color="red")
            )

    c.set(xlabel='Fiber Length (m)', ylabel='Optical Power (dB)', title='OTDR Graph')
    plt.grid()
    plt.show()
```

working without error, 
working nice with your file
but return horizontal line with my .sor  : 

![image](https://github.com/naseriax/pySorReader/assets/20703341/02c4967e-3a2a-4801-b1f8-12de4b488eb9)

**Comment by naseriax** [comment]
Hi,
Thanks for your input,

The problem is that in your sor file, KeyEvents section is before DataPts
section, while in my sor files it after the DataPts section.

I need to do some changes to adopt this sor file type.

**Comment by naseriax** [comment]
Hi,
2 problems were addressed and the file can be processed with no error.

![image](https://github.com/naseriax/pySorReader/assets/54062738/ec35498d-da7b-4644-8c05-c5f2da9d9668)

**Comment by Mglt-b** [comment]
Ohhh so good ! you'r the best
Have 20k+ sor generate by different companies and OTDR
If I have a problem with some of them I would not hesitate to raise the problem so that your program is versatile.

Just another thing, I don't know this lib to display the graphs, it would be possible to add the data extracted from the JSON on the side for example? And tab with events ?
like : https://marmoo.de/coding/otdr/

**Comment by naseriax** [comment]
Please note that the values in the Key event section are still not totally accurate. Checking to find the problem.
The suggestion on the UI looks interesting, If I find some time, will check.

**Comment by Mglt-b** [comment]
Hello,

Problem with this loss :
[NRO_01194_00001-1-056-1550-OE-BRD_01194_01008.zip](https://github.com/naseriax/pySorReader/files/12451690/NRO_01194_00001-1-056-1550-OE-BRD_01194_01008.zip)

![image](https://github.com/naseriax/pySorReader/assets/20703341/feb2c00a-e759-42b2-9eb2-cb0bca97b93a)

65dB ?

Have to add these requirements : 
```python
import json
from datetime import datetime
import matplotlib.pyplot as plt
import re
from textwrap import wrap
```

Its possible to reduce red arrows size ? When zooming, they disappear

thanks for work !

**Comment by naseriax** [comment]
Hi,

Well, Forgot to add the imports, thanks for the heads-up!

That 65dB loss is something I should check. It is reported as negative
value in other apps so I think that’s why my code is calculating it
differently, will check.

**Comment by naseriax** [comment]
The negative loss value issue has been addressed.

**Comment by naseriax** [comment]
Hi,

The difference we see in some values is related to the version of the OTDR core module.
You can look for the value of BellCoreVersion of the sor file in different apps (and my script).

My script was developed to parse BellCoreVersion 2.1 and it does the parsing accurately in most cases.
The file you provided is v2.0 which has some differences in the file structure.That's why we see the unexpected values in the output.

This is just for you know what to look for in case you find some inaccuracy.

I will try to make it compatible with v2.0 gradually.
